on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: "a17db4c9a782427c999b22c8b9b2ecb98e7bd3b3d5c5413c860d9d37edb3712c"
          SENTRY_ORG: "dragonfruit-dev"
          SENTRY_PROJECT: "javascript-react"
          SENTRY_LOG_LEVEL: debug
          # SENTRY_URL: https://sentry.io/
        with:
          environment: "production"
          sourcemaps: "./build/static/"
          version: "githubactions@4.0.0"
          url_prefix: "~/static"