on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: "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"
          SENTRY_ORG: "dragonfruit-dev"
          SENTRY_PROJECT: "javascript-react"
          SENTRY_LOG_LEVEL: debug
          # SENTRY_URL: https://sentry.io/
        with:
          environment: "production"
          sourcemaps: "./build/static/"
          version: "githubactions@3.0.0"
          url_prefix: "~/static"